#baseURL = "http://example.org/"
languageCode = "en-us"
DefaultContentLanguage = "ja"
title = "Daily Santaro "
theme = "dimension"
#googleAnalytics = "UA-"

[params]
    author = "Kotaro Sonoda"
    description = ""
    copyrightPublishYear = "2020"
    # copyrightText = "<a href=\"https://dmitrypechnikov.xyz\">Dmitry Pechnikov</a>"

    # disableLogo = false
    # logoImage = ""
    # logoIcon = "gem"
    # titleFontSize = "2.25rem"
    # subtitleFontSize = "0.8rem"
    # baseFontSize = "1.0rem"
    # overlayOpacityPercentage = "50"
    # disableImageOverlay = false
    # modalWidth = "40rem"

    # customCSS = "custom.css"


[languages]
    [languages.en]
        languageName = "English"
        weight = 1

    [languages.ja]
        languageName = "Japanese"
        weight = 2

[permalinks]
    "" = "/#:filename"
